# Define the base image
FROM public.ecr.aws/lambda/python:3.9

# Install packages
RUN pip install numpy

# Copy your application code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (app.lambda_handler)
CMD ["lambda_function.lambda_handler"]
