# Define the base image
FROM public.ecr.aws/lambda/python:3.9

# Install system dependencies required by LightGBM
RUN yum update -y \
    && yum install -y \
       gcc \
       gcc-c++ \
       make \
       cmake \
       libgomp \
       && yum clean all 

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy application code
COPY lambda_function.py train.py config.json db_helpers.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (app.lambda_handler)
CMD ["lambda_function.lambda_handler"]
